# Copyright 2019 Biomedical Data Science Lab, Universitat Politècnica de València (Spain) - Department of Biomedical Informatics, Harvard Medical School (US)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if (!require('shiny')) install.packages("shiny", repos = "http://cran.us.r-project.org")
if (!require('shinyjs')) install.packages("shinyjs", repos = "http://cran.us.r-project.org")
if (!require('shinydashboard')) install.packages("shinydashboard", repos = "http://cran.us.r-project.org")
if (!require('shinythemes')) install.packages("shinythemes", repos = "http://cran.us.r-project.org")
if (!require('shinycssloaders')) install.packages("shinycssloaders", repos = "http://cran.us.r-project.org")
if (!require('tippy')) install.packages("tippy", repos = "http://cran.us.r-project.org")
if (!require('plotly')) install.packages("plotly", repos = "http://cran.us.r-project.org")
if (!require('zoo')) install.packages("zoo", repos = "http://cran.us.r-project.org")
if (!require('xts')) install.packages("xts", repos = "http://cran.us.r-project.org")
if (!require('viridis')) install.packages("viridis", repos = "http://cran.us.r-project.org")
if (!require('RColorBrewer')) install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")
if (!require('shiny')) install.packages("shiny", repos = "http://cran.us.r-project.org")

library(shiny)
library(shinyjs)
library(shinydashboard)
library(shinythemes)
library(shinycssloaders)
library(tippy)
library(plotly)
library(zoo)
library(xts)
library(viridis)
library(RColorBrewer)
library(EHRtemporalVariability)


options( shiny.maxRequestSize=1024*1024^2 ) # 1 GB Max upload size
MAX_HEATMAP_VAL = 200
DEFAULT_HEATMAP_VAL = 20

######################################################################################
# Define UI for data upload app ----
######################################################################################

ui <- fluidPage(
  navbarPage(
    title = "", id="main_panel",
    theme = shinythemes::shinytheme("cosmo"),
    tabPanel(value="main",
             title = p("EHRtemporalVariability", 
                       style = "font-size: 20px; padding-bottom: -0.5cm"),
             fluidRow( 
               column ( 6,
                        sidebarLayout(
                          sidebarPanel(
                            h3( "Welcome to the EHRtemporalVariability Shiny App!" ),
                            br(),
                            tags$p(HTML( "Variability in healthcare processes, protocols or due to the system or human biases, can be a potential bias for the reuse of Electronic Health Records (EHRs), where unexpected batch-effects can be introduced. EHRtemporalVariability is an open-source R-package and Shiny-app for exploring and undercovering the effects of time in the statistical distributions of EHRs. EHRtemporalVariability batches and visualizes EHRs temporal-evolution through dynamic heatmaps and non-parametric-information-geometry plots for coded, numerical and multivariate EHR data." ) ),
                            tags$p(HTML(
                              "R package GitHub repo: <a href=\"https://github.com/hms-dbmi/EHRtemporalVariability\" target=\"_blank\">https://github.com/hms-dbmi/EHRtemporalVariability</a>."
                            )),
                            tags$p(HTML(
                              "Shiny app GitHub repo: <a href=\"https://github.com/hms-dbmi/EHRtemporalVariability-shiny\" target=\"_blank\">https://github.com/hms-dbmi/EHRtemporalVariability-shiny</a>."
                            )),
                            br(),
                            h5( HTML("To begin, you can use any of the next options:\n\n" ) ),
                            
                            tags$p(
                              HTML(
                                "<ol start='1'> <li>\"Demo with real data\" explores a case study of the app capabilities with the US National Hospital Discharge Survey open dataset.</li>
                                <li>\"Load your .RData\" takes an .RData file generated by the EHRtemporalVariability R package to display and explore its results.</li>
                                <li>\"Load your csv\" takes a raw data .csv file as the input for a new analysis, where some format parameters are available.</li>
                                </ol>"
                              )
                            ),
                            tags$p(HTML(
                              "For further details see our <a href=\"https://htmlpreview.github.com/?https://github.com/hms-dbmi/EHRtemporalVariability/master/vignettes/EHRtemporalVariability.html\" target=\"_blank\">vignette</a>, <a href=\"https://github.com/hms-dbmi/EHRtemporalVariability#EHRtemporalVariability\" target=\"_blank\">case study</a> and <a href=\"https://github.com/hms-dbmi/EHRtemporalVariability#Citation\" target=\"_blank\"> publications</a>."
                            )),
                            tags$p(HTML(
                              "If you use EHRtemporalVariability, please cite:"
                            )),
                            tags$p(HTML(
                              "<blockquote style='font-size:14px'>Carlos Sáez, Alba Gutiérrez-Sacristán, Paul Avillach, Juan M García-Gómez.
                              EHRtemporalVariability: delineating unknown reference changes in Electronic Health Records over time.
                              (Submitted) </blockquote>"
                            )),
                            width = 12
                          ),
                          #mainPanel(img(src = 'testing.png', align = "center", width="1000px", height="500px"))
                          mainPanel(img(src = 'logos.png', align = "center", width="646px", height="70px"))
                          
                        )
               ), column(
                 6,
                 tabsetPanel(
                   id = "tabsetLoadOptions",
                   tabPanel("Demo with real data",
                            mainPanel(
                              tags$h4(HTML("<u>NHDS data</u>")),
                              p(
                                "The National Hospital Discharge Survey (NHDS), which was conducted annually from 1965-2010, was a national probability survey designed to meet the need for information on characteristics of inpatients discharged from non-Federal short-stay hospitals in the United States. Data from the NHDS are available annually and are used to examine important topics of interest in public health and for a variety of activities by governmental, scientific, academic, and commercial institutions. This demo includes a total of 3,257,718 hospital discharges between 2000 and 2010. For more information visit", HTML("<a href=\"http://www.cdc.gov/nchs/nhds/index.htm\" target=\"_blank\">https://www.cdc.gov/nchs/nhds/index.htm</a>"),"."
                              ),
                              br(),
                              width = 12
                              ),
                            column(12,
                                   sidebarLayout(
                                     sidebarPanel(
                                       # fluidRow(selectInput("demodatasetSelection",  
                                       #                      label = "Select analysis period", 
                                       #                      choices = c("Year", "Month", "Week"), 
                                       #                      selected = "Month")),
                                       width = 12,
                                       fluidRow(
                                                tags$button(id="confirm0", 
                                                            type="button", 
                                                            class="btn action-button btn-large btn-primary", 
                                                            HTML('<i class="icon-star"></i>Go to the demo!'))
                                       )
                                     ),
                                     mainPanel( )
                                   ))),
                   tabPanel("Load your .RData",
                            mainPanel(
                              tags$h3(HTML("<u>Instructions</u>")),
                              p(
                                HTML("Using the EHRtemporalVariability R package allows more flexibility in raw data formatting and variable preprocessing, such as formatting ICD-9 codes, selecting or deriving specific variables, or even reducing the dimensionality of data. The resultant objects of classes 'DataTemporalMap' and 'IGTProjection' can be used as input for the shiny App. You can save them in a file to be uploaded herein by typing: save( dataTemporalMaps, igtProjections, file = “myResults.RData ). For more information read the accompaining <a href=\"https://htmlpreview.github.com/?https://github.com/hms-dbmi/EHRtemporalVariability/master/vignettes/EHRtemporalVariability.html\" target=\"_blank\">vignette</a>/<a href=\"https://github.com/hms-dbmi/EHRtemporalVariability#EHRtemporalVariability\" target=\"_blank\">case study</a>.")
                              ),
                              br(), p(img(src = 'warning.png', align = "rigth", width="25px", height="20px"),
                                      "Do not upload patient-level data", 
                                      img(src = 'warning.png', align = "rigth", width="25px", height="20px")
                                      , style="color:red;"),
                              br(),
                              p(
                                "To see what a correctly formatted data set looks like download the NHDS demo file below (limited to a 10% random subsample of the NHDS data between 2000 and 2010)."
                              ),
                              tags$a(href = "https://github.com/hms-dbmi/EHRtemporalVariability-DataExamples/raw/master/variabilityDemoNHDS.RData", "Download the NHDS RData here!"),
                              br(),
                              br(),
                              width = 12
                            ),
                            column(12,
                                   sidebarLayout(
                                     sidebarPanel(
                                       
                                       fluidRow(
                                         # Input: Select a file ----
                                         fileInput("fileRData", "RData file",
                                                   multiple = FALSE,
                                                   accept = c("RData")), 
                                         textOutput("rdataLoaded")),
                                       width = 12,
                                       
                                       fluidRow(br(),
                                                tags$button(id="confirm1", 
                                                            type="button", 
                                                            class="btn action-button btn-large btn-primary", 
                                                            HTML('<i class="icon-star"></i>Plot!'))
                                       )
                                     ),
                                     mainPanel( )
                                   ))), 
                   tabPanel("Load your csv",
                            mainPanel(
                              tags$h3(HTML("<u>Instructions</u>")),
                              p(
                                "To use this method, begin by uploading a correctly formatted .csv file.
                                A correctly formatted .csv file is that where each line is a data record, each consisting of one or more fields separated by a delimiter character. After uploading the file, choose the correct separator. If the elements in each
                                column are seperated by a ' , ' choose comma, by a ' ; ' choose semicolon, or by tabs choose tab."
                              ),
                              br(),
                              p(img(src = 'warning.png', align = "rigth", width="25px", height="20px"),
                                "Do not upload patient-identifiable data", 
                                img(src = 'warning.png', align = "rigth", width="25px", height="20px")
                                , style="color:red;"),
                              br(),
                              p(
                                "To see what a correctly formatted data set looks like download the NHDS demo file below (limited to a 10% random subsample of the NHDS data between 2000 and 2010)."
                              ),
                              tags$a(href = "http://github.com/hms-dbmi/EHRtemporalVariability-DataExamples/raw/master/nhdsSubset.csv", "Download (right-click and 'save as') the NHSD csv demo file here!"),
                              br(),
                              br(),
                              width = 12
                            ),
                            column(12,
                                   sidebarLayout(
                                     sidebarPanel(
                                       
                                       fluidRow(
                                         sidebarPanel(
                                           fluidRow(
                                             # Input: Select a file ----
                                             fileInput("fileCSV", "CSV File",
                                                       multiple = FALSE,
                                                       accept = c("text/csv",
                                                                  "text/comma-separated-values,text/plain",
                                                                  ".csv"))),
                                           # Horizontal line ----
                                           tags$hr(),
                                           width = 12,
                                           
                                           # Input: Checkbox if file has header ----
                                           column( 3, 
                                                   checkboxInput("header", "Header", TRUE)
                                           )
                                           ,
                                           
                                           # Input: Select separator ----
                                           column(3,
                                                  radioButtons("sep", "Separator",
                                                               choices = c("Comma" = ",",
                                                                           "Semicolon" = ';',
                                                                           "Tab" = "\t"),
                                                               selected = ',')
                                           )
                                           ,
                                           
                                           
                                           # Input: Select quotes ----
                                           column( 3, 
                                                   radioButtons("quote", "Quote",
                                                                choices = c(None = "",
                                                                            "Double Quote" = '"',
                                                                            "Single Quote" = "'"),
                                                                selected = '"')
                                           ),
                                           
                                           # Input: Checkbox to show forst lines of the table ----
                                           column( 3, 
                                                   checkboxInput("showTable", "Show the data loaded", TRUE)
                                           )
                                           ,
                                           fluidRow(
                                             column(3, uiOutput("dateColumn")), 
                                             column(3, uiOutput("dateFormat")),
                                             column(3, uiOutput("analysisPeriod"))
                                           ), 
                                           tippy_this(element = "dateFormat",
                                                      tooltip = "%y -> Year without century (00–99) <br>
                                                      %Y -> Year with century (0000-9999) <br>
                                                      %m -> Month as decimal number (01–12) <br>
                                                      %d -> Day of the month as decimal number (01–31)",
                                                      placement = "right",
                                                      arrow = TRUE),
                                           
                                          fluidRow(br(),
                                                   withSpinner( uiOutput("button") ) 
                                                   )
                                           
                                         ))
                                       , 
                                       width = 12
                                     ), 
                                     #mainPanel( withSpinner( tableOutput("contents")) )
                                     mainPanel( tableOutput( "contents") )
                                   ))
                   )
                   
                 )
               ))
    ),
    tabPanel( value="variability_plot",
              p("Plot Results"),
              
              sidebarLayout(
                # Sidebar panel for inputs ----
                sidebarPanel(
                  fluidRow(
                    uiOutput("variableValue"),
                    uiOutput("daterangeValues"),
                    uiOutput("heatmapvalues"),
                    uiOutput("maxheatmapvaluesSlider"),
                    uiOutput("heatmapSorting"),
                    uiOutput("radioButtonsHeatmapType"),
                    uiOutput("igtdimensions"),
                    uiOutput("igtdateselectionmethod"),
                    # Input: Selector for color palette
                    selectInput(inputId = "colorpalette",
                                label = "Choose a color palette:",
                                choices = c("Spectral", "Viridis", "Magma", "Viridis-reversed", "Magma-reversed"),
                                selected = "Spectral"),
                    uiOutput("download")
                  )
                ),
                # Main panel for displaying outputs ----
                mainPanel(
                  
                  # Output: Tabset w/ plot, summary, and table ----
                  tabsetPanel(
                    id = "tabsetPlots",          
                    type = "tabs",
                              tabPanel("Temporal heatmap",
                                       value = "temporalMap",
                                       br(),
                                       withSpinner(plotlyOutput("datatemporalheatmap"))),
                              tabPanel("IGT plot",
                                       value = "igtPlot",
                                       br(),
                                       withSpinner(plotlyOutput("igtplot")),
                                       tags$figcaption(uiOutput("igtplotcaption"), align = "center")),
                              tabPanel("Temporal heatmap + IGT plot",
                                       value = "temporalMapANDigtPlot",
                                       br(),
                                       withSpinner(plotlyOutput("datatemporalheatmap3")), 
                                       hr(),
                                       withSpinner(plotlyOutput("igtplot3")),
                                       tags$figcaption(uiOutput("igtplotcaption3"), align = "center"))
                  )
                )
              )
    )
  )
)

######################################################################################
# Define server #
######################################################################################

server <- function(input, output, session) {
  
  attr(input, "readonly") <- FALSE
  dataValues <- reactiveValues()
  
  loadfile <- reactive({
    read.csv(input$fileCSV$datapath,
             header = input$header,
             sep = input$sep,
             quote = input$quote)
  })
  
  output$contents <- renderTable({
    
    # input$fileCSV will be NULL initially. After the user selects
    # and uploads a file, head of that data file by default,
    # or all rows if selected, will be shown.
    
    req(input$fileCSV)
    
    # when reading semicolon separated files,
    # having a comma separator causes `read.csv` to error
    tryCatch(
      {
        df <- loadfile()
      },
      error = function(e) {
        # return a safeError if a parsing error occurs
        stop(safeError(e))
      }
    )
    
    if(input$showTable == TRUE) {
      return(head(df))
    }
    
  })
  
  output$dateColumn <- renderUI({
    req(input$fileCSV)
    df <- loadfile()
    selectInput("colnameSelected", label = "Select date column" , 
                choices = c(colnames( df  ), " "), selected = " " )
  })
  
  output$button <- renderUI({
    req( input$fileCSV)
    df <- loadfile()
    #if( input$colnameSelected != " "){
      tags$button(id="confirm2", 
                  type="button", 
                  class="btn action-button btn-large btn-primary", 
                  HTML('<i class="icon-star"></i>Run the analysis & Plot Results!'))
    #}
    
  })
  
  output$dateFormat <- renderUI({
    req(input$fileCSV)
    df <- loadfile()
    selectInput("dateFormatSelected", label = "Select date format", 
                choices = c("%y/%m/%d","%Y/%m/%d", "%d/%m/%y", "%d/%m/%Y", 
                            "%y-%m-%d","%Y-%m-%d", "%d-%m-%y", "%d-%m-%Y", 
                            "%y/%m", "%Y/%m","%m-%Y","%m-%y","%y", "%Y", " " ), selected = " ")
  })
  
  output$analysisPeriod <- renderUI({
    req(input$fileCSV)
    df <- loadfile()
    selectInput("analysisPeriodSelected",  label = "Select analysis period", 
                choices = c("year", "month", "week", " "), selected = " ")
  })
  
  output$rdataLoaded <- renderText( {
    if(! is.null( dataValues$probMaps ) ){
      "File uploaded!"
    }else{
      "Please upload an RData file"
    }})
  
  observeEvent(input$confirm0, {
    senv <- new.env()
    # if( input$demodatasetSelection == "Month"){
    #   load(system.file("extdata",
    #                    "variabilityDemoNHDS_m.RData",
    #                    package = "EHRtemporalVariability"), senv)
    # }else if( input$demodatasetSelection == "Year"){
    #   load(system.file("extdata",
    #                    "variabilityDemoNHDS_y.RData",
    #                    package = "EHRtemporalVariability"), senv)
    #   
    # }else if( input$demodatasetSelection == "Week"){
    #   load(system.file("extdata",
    #                    "variabilityDemoNHDS_w.RData",
    #                    package = "EHRtemporalVariability"), senv)
    # }
    load(system.file("extdata",
                     "variabilityDemoNHDS.RData",
                     package = "EHRtemporalVariability"), senv)
    message(ls())
    dataValues$probMaps <- senv$probMaps
    dataValues$igtProjs <- senv$igtProjs
    
    updateTabsetPanel(session, "main_panel",
                      selected = "variability_plot")
    
  })
  
  observeEvent(input$confirm1, {
    senv <- new.env()
    load(input$fileRData$datapath, senv)
    message(ls())
    dataValues$probMaps <- senv$probMaps
    dataValues$igtProjs <- senv$igtProjs
    
    # output$rdataLoaded <- renderText("File uploaded!")
    
    updateTabsetPanel(session, "main_panel",
                      selected = "variability_plot")
    
  })
  
  observeEvent(input$confirm2, {
    
    withProgress(message = 'Running the analysis', value = 0, {

        incProgress(detail = "Step 1:3 -> Formatting the date")
      
    
    #transform the date column
    ourInput <- EHRtemporalVariability::formatDate( input = loadfile(), 
                                           dateColumn = input$colnameSelected,
                                           dateFormat = input$dateFormatSelected)
    message( lapply(ourInput, class))
    message( head(ourInput$date))
    
    incProgress(detail = "Step 2:3 -> Estimating DataTemporalMap")
    probMaps <- estimateDataTemporalMap(data           = ourInput, 
                                        dateColumnName = input$colnameSelected, 
                                        period         = input$analysisPeriodSelected)
    
    incProgress(detail = "Step 3:3 -> Calculating igtProjections")
    
    igtProjs <- lapply(probMaps, estimateIGTProjection)
    names(igtProjs) = names(probMaps)
    
    dataValues$probMaps <- probMaps
    dataValues$igtProjs <- igtProjs

    })
    updateTabsetPanel(session, "main_panel",
                      selected = "variability_plot")
  })
  
  ###
  output$download <- renderUI({
    if(!is.null(input$confirm1) & !is.null(input$confirm2)) {
      downloadButton('OutputFile', 'Save analysis results')
    }
  })
  
  output$OutputFile <- downloadHandler(
    filename = "EHRoutputData.RData",
    content = function(con) {
      
      withProgress(message = 'RData file ready:', value = 0, {
        
        incProgress(detail = "Download in progress")
      if(! is.null( dataValues$probMaps ) && ! is.null( dataValues$igtProjs )){
        probMaps = dataValues$probMaps
        igtProjs = dataValues$igtProjs
        save(probMaps, igtProjs, file=con)
      }
      }
    )}
  )
  
  
  observeEvent(input$variable, {
    if (input$variable != ""){
      dataValues$heatmapvalueMin = 1
      dataValues$heatmapvalueMax = switch(dataValues$probMaps[[input$variable]]@variableType, "character" = DEFAULT_HEATMAP_VAL, "factor" = DEFAULT_HEATMAP_VAL, "numeric" = nrow(dataValues$probMaps[[input$variable]]@support), "integer" = nrow(dataValues$probMaps[[input$variable]]@support), "Date" = nrow(dataValues$probMaps[[input$variable]]@support))
      if (dataValues$heatmapvalueMax > nrow(dataValues$probMaps[[input$variable]]@support) ){
        dataValues$heatmapvalueMax = nrow(dataValues$probMaps[[input$variable]]@support)
      }
    }
  })
  
  observeEvent(input$heatmapvaluesrange, {
    dataValues$heatmapvalueMin = input$heatmapvaluesrange[1]
    dataValues$heatmapvalueMax = input$heatmapvaluesrange[2]
  })
  
  output$variableValue <- renderUI({
    
    selectInput(inputId = "variable", 
                label = "Choose a variable:", 
                choices =  names(dataValues$probMaps)
    )
    
  })
  
  output$igtdimensions <- renderUI({
    if(! is.null( dataValues$probMaps ) && input$tabsetPlots %in% c("igtPlot","temporalMapANDigtPlot") ){
      radioButtons("dim",
                   "IGT plot dimensions:",
                   c('2D' = 2, '3D (slower but more informative)' = 3), 
                   selected = 2
                   # selected = ifelse( dataValues$probMaps[[1]]@period == "week", 2, 3)
                   )
    }
  })
  
  output$igtdateselectionmethod <- renderUI({
    if(! is.null( dataValues$probMaps ) && input$tabsetPlots %in% c("igtPlot","temporalMapANDigtPlot") ){
      radioButtons("igtdateselection",
                   "IGT plot date selection method:",
                   c("Crop from full embedding (faster but less accurate)" = "crop", "Recalculate embedding (slower but more accurate)" = "recalc"), 
                   selected = "crop"
      )
    }
  })
  
  output$daterangeValues <- renderUI({
      if(! is.null(dataValues$probMaps) ){
        sliderInput("daterange", "Date selection:",
                    min = min(dataValues$probMaps[[1]]@dates),
                    max = max(dataValues$probMaps[[1]]@dates),
                    value = c(min(dataValues$probMaps[[1]]@dates), max = max(dataValues$probMaps[[1]]@dates))
        )
      }else{
        sliderInput("daterange", "Date selection:",
                    min = as.Date("1990-01-01"),
                    max = Sys.Date(),
                    value = c( as.Date( "1990-01-01" ), Sys.Date() )
        )

      }})
  
  # output$daterangeValues <- renderUI({
  #     if(! is.null(dataValues$probMaps) ){
  #       dateRangeInput("daterange", "Date range:",
  #                      start  = min(dataValues$probMaps[[1]]@dates),
  #                      end    = max(dataValues$probMaps[[1]]@dates),
  #                      min    = min(dataValues$probMaps[[1]]@dates),
  #                      max    = max(dataValues$probMaps[[1]]@dates),
  #                      startview = "year",
  #                      weekstart = 0)
  #     }else{
  #       dateRangeInput("daterange", "Date range:",
  #                      start  = "1990-01-01",
  #                      end    = NULL,
  #                      min    = "1990-01-01",
  #                      max    = NULL,
  #                      startview = "year",
  #                      weekstart = 0)
  #     }
  #   })
  
  output$heatmapvalues <- renderUI({
    if(!is.null( dataValues$probMaps ) && !is.null(input$variable) && input$variable != "" && input$tabsetPlots %in% c("temporalMap","temporalMapANDigtPlot") ){
      defaultvals = c(dataValues$heatmapvalueMin, dataValues$heatmapvalueMax)
      if(dataValues$probMaps[[input$variable]]@variableType %in% c("character", "factor")){
        maxval = min(nrow(dataValues$probMaps[[input$variable]]@support),input$maxheatmapvalues)
      }
      else{
        maxval = ifelse(nrow(dataValues$probMaps[[input$variable]]@support) > MAX_HEATMAP_VAL, MAX_HEATMAP_VAL, nrow(dataValues$probMaps[[input$variable]]@support))
      }
      sliderInput("heatmapvaluesrange",
                  "Temporal heatmap values range:",
                  min = 1,
                  max = maxval,
                  value = defaultvals,
                  step = 1
      )}
    
  })
  
  output$maxheatmapvaluesSlider <- renderUI({
    if(!is.null(input$variable) && input$variable != "" && input$tabsetPlots %in% c("temporalMap","temporalMapANDigtPlot"))
    {
      if(dataValues$probMaps[[input$variable]]@variableType %in% c("character", "factor") && nrow(dataValues$probMaps[[input$variable]]@support) > MAX_HEATMAP_VAL)
      {
        if(! is.null( dataValues$probMaps ) ){
          minval = ifelse(nrow(dataValues$probMaps[[input$variable]]@support) > MAX_HEATMAP_VAL, MAX_HEATMAP_VAL, nrow(dataValues$probMaps[[input$variable]]@support))
          sliderInput("maxheatmapvalues",
                      "Temporal heatmap values limit:",
                      min = minval,
                      max = nrow(dataValues$probMaps[[input$variable]]@support),
                      value = minval,
                      step = 1
          )}
      }
    }
  })
  
  output$heatmapSorting <- renderUI({
    if(!is.null(input$variable) && input$variable != "" && input$tabsetPlots %in% c("temporalMap","temporalMapANDigtPlot"))
    {
      if(dataValues$probMaps[[input$variable]]@variableType %in% c("character", "factor"))
      {
        radioButtons("heatmapSortingOption",
                     "Temporal heatmap values sorting (only in categorical):",
                     c("Frequency" = "frequency", "Alphabetical" = "alphabetical"), 
                     selected = "frequency"
        )
      }
    }
  })
  
  output$radioButtonsHeatmapType <- renderUI({
    if(!is.null(input$variable) && input$variable != "" && input$tabsetPlots %in% c("temporalMap","temporalMapANDigtPlot"))
    {
      radioButtons("heatmaptype", "Temporal heatmap data type:",
                   c("Probability (relative frequencies)" = "probability",
                     "Counts (absolute frequencies)" = "counts")
      )
    }
  })
  
  output$datatemporalheatmap <- output$datatemporalheatmap3 <- renderPlotly({
    if( ! is.null( dataValues$probMaps )  && !is.null(input$variable) && input$variable != "" && !is.null(input$daterange[1]) && !is.null(input$colorpalette) && !is.null(input$heatmaptype)){
      
      if (is.null(input$heatmapSortingOption)){
        sortingMethod = 'frequency'
      } else{
        sortingMethod = input$heatmapSortingOption
      }
      
      plotDataTemporalMap(
        dataValues$probMaps[[input$variable]],
        startValue = ifelse(is.null(dataValues$heatmapvalueMin),1,dataValues$heatmapvalueMin),
        endValue   = ifelse(is.null(dataValues$heatmapvalueMax),switch(dataValues$probMaps[[input$variable]]@variableType, "character" = DEFAULT_HEATMAP_VAL, "factor" = DEFAULT_HEATMAP_VAL, "numeric" = nrow(dataValues$probMaps[[input$variable]]@support), "integer" = nrow(dataValues$probMaps[[input$variable]]@support)), dataValues$heatmapvalueMax),
        startDate = input$daterange[1],
        endDate = input$daterange[2], 
        sortingMethod = sortingMethod,
        colorPalette = input$colorpalette,
        absolute = switch(input$heatmaptype, "probability" = FALSE, "counts" = TRUE ))
    }
    else if (!is.null( dataValues$probMaps )){
      plotly_empty()
    }
    else{
      stop( "Please go back to the previous page and upload your data" )
    }  
    
  } )
  
  # output$igtplot <- output$igtplot3 <- renderPlotly({
  #   
  #   if( !is.null( dataValues$probMaps )  && !is.null(input$variable) && input$variable != "" && !is.null(input$daterange[1]) && !is.null(input$dim) && !is.null(input$colorpalette)){
  #     igtProj <- estimateIGTProjection(EHRtemporalVariability::trimDataTemporalMap(dataValues$probMaps[[input$variable]], startDate = input$daterange[1], endDate = input$daterange[2] ))
  #     plotIGTProjection( igtProj, 
  #                        dimensions = input$dim,
  #                        colorPalette = input$colorpalette)
  #   }else if (!is.null( dataValues$probMaps )){
  #     plotly_empty()
  #   }
  #   else{
  #     stop( "Please go back to the previous page and upload your data" )
  #   }   
  # })
  
  output$igtplot <- output$igtplot3 <- renderPlotly({
    
    if( !is.null( dataValues$probMaps )  && !is.null(input$variable) && input$variable != "" && !is.null(input$daterange[1]) && !is.null(input$dim) && !is.null(input$colorpalette)){
      if(input$igtdateselection == 'crop'){
        plotIGTProjection( dataValues$igtProjs[[input$variable]], 
                           dimensions = input$dim,
                           startDate = input$daterange[1],
                           endDate = input$daterange[2],
                           colorPalette = input$colorpalette)
      }
      else{ # input$igtdateselection == 'recalc'
        igtProj <- estimateIGTProjection(EHRtemporalVariability::trimDataTemporalMap(dataValues$probMaps[[input$variable]], startDate = input$daterange[1], endDate = input$daterange[2] ))
        plotIGTProjection( igtProj,
                           dimensions = input$dim,
                           colorPalette = input$colorpalette)
      }
      
    }else if (!is.null( dataValues$probMaps )){
      plotly_empty()
    }
    else{
      stop( "Please go back to the previous page and upload your data" )
    }   
  })
  
  output$igtplotcaption <- output$igtplotcaption3 <- renderUI({
    if (!is.null( dataValues$probMaps ) && !is.null(input$variable) && input$variable != "") {
      caption <- switch(dataValues$probMaps[[input$variable]]@period,
                        "week" = "Text labels are formatted as 'yymw', where 'yy' is a 2 digit year, 'm' is an abbreviated month* and 'w' is an ISO week number in 1-2 digit. Coloring is according to the season (yearly).<br>*Month abbreviations: {'J', 'F', 'M', 'A', 'm', 'j', 'x', 'a', 'S', 'O', 'N', 'D'}.",
                        "month" = "Text labels are formatted as 'yym', where 'yy' is a 2 digit year and 'm' is an abbreviated month*. Coloring is according to the season (yearly).<br>*Month abbreviations: {'J', 'F', 'M', 'A', 'm', 'j', 'x', 'a', 'S', 'O', 'N', 'D'}.",
                        "year" = "Text labels are formatted as 'yy' (2 digit year). Coloring is according to year.")
      HTML(caption)
    } else {
    } 
  })
}


# Create Shiny app ----
shinyApp(ui, server)